# Generated by Django 5.2.9 on 2025-12-03 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenserequest',
            name='receipt_photo_content_type',
            field=models.CharField(default='image/jpeg', max_length=100, verbose_name='Тип файла'),
        ),
        migrations.AddField(
            model_name='expenserequest',
            name='receipt_photo_name',
            field=models.CharField(default='unknown_receipt.jpg', max_length=255, verbose_name='Имя файла'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='expenserequest',
            name='receipt_photo',
            field=models.BinaryField(verbose_name='Фото чека'),
        ),
    ]
