# Generated by Django 5.2.9 on 2025-12-12 06:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_expenserequest_receipt_photo_content_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenserequest',
            name='status',
            field=models.CharField(choices=[('new', 'Новая'), ('approved', 'Одобрена'), ('paid', 'Выплачена'), ('rejected', 'Отклонена')], default='new', max_length=20, verbose_name='Статус'),
        ),
        migrations.CreateModel(
            name='MoneyRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма')),
                ('justification', models.TextField(verbose_name='Обоснование')),
                ('status', models.CharField(choices=[('new', 'Новый'), ('approved', 'Одобрен'), ('paid', 'Выплачен'), ('rejected', 'Отклонен')], default='new', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('admin_comment', models.TextField(blank=True, null=True, verbose_name='Комментарий финансиста')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.telegramuser', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Запрос денежных средств',
                'verbose_name_plural': 'Запросы денежных средств',
                'ordering': ['-created_at'],
            },
        ),
    ]
